'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { BookOpen, FileUp, GraduationCap, LogOut, Plus, ShieldCheck, Users } from 'lucide-react';
import { getSupabaseClient } from '@/lib/supabase-client';

type Tab = 'overview' | 'academic' | 'resources' | 'showcases';
type Row = { id: string; name?: string; label?: string; category_id?: string; program_id?: string; level_id?: string };
const ADMIN = 'anishkumar.07wi@gmail.com';
const TYPES = ['notes','previous_paper','important_questions','model_paper','lab_manual','assignment','syllabus','question_bank','reference','other'];

export default function AdminPage() {
  const [user,setUser] = useState<any>(null), [allowed,setAllowed] = useState(false), [loading,setLoading] = useState(true);
  const [tab,setTab] = useState<Tab>('overview'), [message,setMessage] = useState('');
  const [categories,setCategories] = useState<Row[]>([]), [programs,setPrograms] = useState<Row[]>([]), [levels,setLevels] = useState<Row[]>([]), [subjects,setSubjects] = useState<Row[]>([]), [resources,setResources] = useState<any[]>([]), [showcases,setShowcases] = useState<any[]>([]), [counts,setCounts] = useState<Record<string,number>>({});
  const [cat,setCat] = useState<Row|null>(null), [program,setProgram] = useState<Row|null>(null), [level,setLevel] = useState<Row|null>(null), [subject,setSubject] = useState<Row|null>(null);
  const [newCat,setNewCat] = useState(''), [newProgram,setNewProgram] = useState(''), [newLevel,setNewLevel] = useState(''), [newSubject,setNewSubject] = useState('');
  const [resource,setResource] = useState({title:'',description:'',type:'notes',year:'',module:'',url:''});
  const [file,setFile] = useState<File|null>(null);

  useEffect(() => {
    const s = getSupabaseClient();
    s.auth.getSession().then(({data}) => { const u=data.session?.user; if(u){setUser(u); verify(u.email||'')} else setLoading(false); });
    const {data:listener}=s.auth.onAuthStateChange((_e,session)=>{ const u=session?.user; if(u){setUser(u);verify(u.email||'')} else {setUser(null);setAllowed(false);setLoading(false)} });
    return () => listener.subscription.unsubscribe();
  },[]);

  async function verify(email:string){ const ok=email.trim().toLowerCase()===ADMIN; setAllowed(ok); if(ok) await loadAll(); setLoading(false); }
  async function loadAll(){
    const s=getSupabaseClient();
    const [c,p,l,su,r,sh]=await Promise.all([
      s.from('academic_categories').select('*').order('sort_order'), s.from('academic_programs').select('*').order('sort_order'),
      s.from('academic_levels').select('*').order('sort_order'), s.from('academic_subjects').select('*').order('sort_order'),
      s.from('academic_resources').select('*').order('created_at',{ascending:false}), s.from('community_showcase').select('*,profiles(full_name,email)').order('created_at',{ascending:false})
    ]);
    setCategories(c.data||[]);setPrograms(p.data||[]);setLevels(l.data||[]);setSubjects(su.data||[]);setResources(r.data||[]);setShowcases(sh.data||[]);
    const tables=['academic_categories','academic_programs','academic_levels','academic_subjects','academic_resources','profiles','community_showcase'];
    const totals=await Promise.all(tables.map(t=>s.from(t).select('*',{count:'exact',head:true}))); setCounts(Object.fromEntries(tables.map((t,i)=>[t,totals[i].count||0])));
  }
  async function chooseCategory(v:Row){setCat(v);setProgram(null);setLevel(null);setSubject(null);const {data}=await getSupabaseClient().from('academic_programs').select('*').eq('category_id',v.id).order('sort_order').order('name');setPrograms(data||[])}
  async function chooseProgram(v:Row){setProgram(v);setLevel(null);setSubject(null);const {data}=await getSupabaseClient().from('academic_levels').select('*').eq('program_id',v.id).order('sort_order').order('name');setLevels(data||[])}
  async function chooseLevel(v:Row){setLevel(v);setSubject(null);const {data}=await getSupabaseClient().from('academic_subjects').select('*').eq('level_id',v.id).order('sort_order').order('name');setSubjects(data||[])}
  async function add(table:string,payload:any,clear:()=>void,label:string){const {error}=await getSupabaseClient().from(table).insert(payload);setMessage(error?.message||label);if(!error){clear();await loadAll()}}
  function slug(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
  async function addResource(e:FormEvent){e.preventDefault();if(!subject||!resource.title.trim()){setMessage('Select a subject and enter a title.');return}if(!file&&!resource.url.trim()){setMessage('Add a file or external URL.');return}const s=getSupabaseClient();let path:string|null=null;if(file){const safe=`${Date.now()}_${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await s.storage.from('learning-assets').upload(`resources/${safe}`,file);if(up.error){setMessage(up.error.message);return}path=up.data.path}const {error}=await s.from('academic_resources').insert({subject_id:subject.id,title:resource.title.trim(),description:resource.description.trim(),resource_type:resource.type,year:resource.year?Number(resource.year):null,module_number:resource.module?Number(resource.module):null,file_path:path,external_url:resource.url.trim()||null,created_by:user.id});setMessage(error?.message||'Resource published.');if(!error){setResource({title:'',description:'',type:'notes',year:'',module:'',url:''});setFile(null);await loadAll()}}
  async function showcase(id:string,status:'approved'|'rejected'){const {error}=await getSupabaseClient().from('community_showcase').update({status}).eq('id',id);setMessage(error?.message||`Showcase ${status}.`);if(!error)await loadAll()}
  async function signOut(){await getSupabaseClient().auth.signOut();location.href='/'}

  if(loading)return <main className="min-h-screen grid place-items-center bg-[#050505] text-slate-400">Checking admin access…</main>;
  if(!user||!allowed)return <main className="min-h-screen grid place-items-center bg-[#050505] p-6"><div className="max-w-md rounded-3xl border border-red-500/20 bg-red-500/5 p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-red-300"/><h1 className="mt-5 text-2xl font-bold text-white">Admin access required</h1><p className="mt-2 text-sm text-slate-400">This workspace is restricted to the configured administrator account.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 font-semibold text-black">Back to Hub4Buddies</Link></div></main>;
  const nav=(v:Tab,label:string)=><button onClick={()=>setTab(v)} className={`rounded-xl px-4 py-2 text-sm ${tab===v?'bg-white text-black':'text-slate-400 hover:text-white'}`}>{label}</button>;
  return <div className="min-h-screen bg-[#050505] text-slate-100"><header className="sticky top-0 z-40 border-b border-white/10 bg-black/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link href="/" className="font-bold">Hub4Buddies <span className="text-xs text-indigo-300">ADMIN</span></Link><nav className="hidden gap-1 md:flex">{nav('overview','Overview')}{nav('academic','Academic')}{nav('resources','Resources')}{nav('showcases','Showcases')}</nav><button onClick={signOut} className="flex items-center gap-2 text-sm text-slate-400"><LogOut className="h-4 w-4"/>Sign out</button></div></header>
  <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">{message&&<div className="mb-5 rounded-xl border border-indigo-400/20 bg-indigo-400/10 p-3 text-sm text-indigo-200">{message}</div>}
  {tab==='overview'&&<><section className="rounded-3xl border border-white/10 bg-gradient-to-br from-indigo-950/40 to-transparent p-7"><p className="text-sm text-indigo-300">CONTROL CENTER</p><h1 className="mt-2 text-4xl font-black">Hub4Buddies Admin</h1><p className="mt-3 max-w-2xl text-slate-400">Manage academic structures, resources and community submissions.</p></section><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Areas',counts.academic_categories,BookOpen],['Programs',counts.academic_programs,GraduationCap],['Resources',counts.academic_resources,FileUp],['Students',counts.profiles,Users]].map(([label,n,Icon])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><Icon className="h-5 w-5 text-indigo-300"/><p className="mt-4 text-3xl font-bold">{n as number}</p><p className="text-sm text-slate-500">{String(label)}</p></div>)}</div></>}
  {tab==='academic'&&<section><h1 className="text-3xl font-bold">Academic Structure</h1><p className="mt-2 text-slate-400">Education Area → Program → Class/Year/Semester → Subject</p><div className="mt-6 grid gap-5 lg:grid-cols-4">{[["Areas",categories,cat,(v:Row)=>chooseCategory(v),newCat,setNewCat,()=>add('academic_categories',{name:newCat.trim(),slug:slug(newCat),sort_order:categories.length+1},()=>setNewCat(''),'Area added.')],["Programs",programs.filter(x=>x.category_id===cat?.id),program,(v:Row)=>chooseProgram(v),newProgram,setNewProgram,()=>cat&&add('academic_programs',{category_id:cat.id,name:newProgram.trim(),slug:slug(newProgram),sort_order:programs.length+1},()=>setNewProgram(''),'Program added.')],["Levels",levels.filter(x=>x.program_id===program?.id),level,(v:Row)=>chooseLevel(v),newLevel,setNewLevel,()=>program&&add('academic_levels',{program_id:program.id,name:newLevel.trim(),label:newLevel.trim(),level_number:Number(newLevel)||null,sort_order:levels.length+1},()=>setNewLevel(''),'Level added.')],["Subjects",subjects.filter(x=>x.level_id===level?.id),subject,(v:Row)=>setSubject(v),newSubject,setNewSubject,()=>level&&add('academic_subjects',{level_id:level.id,name:newSubject.trim(),sort_order:subjects.length+1},()=>setNewSubject(''),'Subject added.')]].map(([title,items,selected,onSelect,value,setValue,onAdd])=><div key={String(title)} className="rounded-2xl border border-white/10 p-4"><h2 className="font-semibold">{String(title)}</h2><div className="mt-3 space-y-2">{(items as Row[]).map(x=><button key={x.id} onClick={()=>onSelect(x)} className={`block w-full rounded-lg p-2 text-left text-sm ${selected&&((selected as Row).id===x.id)?'bg-indigo-500/20 text-indigo-200':'text-slate-400 hover:bg-white/5'}`}>{x.label||x.name}</button>)}</div><div className="mt-4 flex gap-2"><input value={value as string} onChange={e=>(setValue as any)(e.target.value)} placeholder="Add new" className="min-w-0 flex-1 rounded-lg bg-white/5 px-2 py-2 text-xs"/><button onClick={onAdd as any} className="rounded-lg bg-white px-3 text-black"><Plus className="h-4 w-4"/></button></div></div>)}</div></section>}
  {tab==='resources'&&<section><h1 className="text-3xl font-bold">Resource Manager</h1><p className="mt-2 text-slate-400">Select a subject in Academic, then publish resources.</p>{subject?<form onSubmit={addResource} className="mt-6 max-w-2xl space-y-3 rounded-2xl border border-white/10 bg-white/[.03] p-6"><div className="rounded-xl bg-indigo-500/10 p-3 text-sm text-indigo-200">Subject: <b>{subject.name}</b></div><input required value={resource.title} onChange={e=>setResource({...resource,title:e.target.value})} placeholder="Resource title" className="w-full rounded-xl bg-black/40 px-4 py-3 text-sm"/><textarea value={resource.description} onChange={e=>setResource({...resource,description:e.target.value})} placeholder="Description" className="w-full rounded-xl bg-black/40 px-4 py-3 text-sm"/><select value={resource.type} onChange={e=>setResource({...resource,type:e.target.value})} className="w-full rounded-xl bg-black/40 px-4 py-3 text-sm">{TYPES.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input inputMode="numeric" value={resource.year} onChange={e=>setResource({...resource,year:e.target.value})} placeholder="Year" className="rounded-xl bg-black/40 px-4 py-3 text-sm"/><input inputMode="numeric" value={resource.module} onChange={e=>setResource({...resource,module:e.target.value})} placeholder="Module" className="rounded-xl bg-black/40 px-4 py-3 text-sm"/></div><input type="url" value={resource.url} onChange={e=>setResource({...resource,url:e.target.value})} placeholder="External URL" className="w-full rounded-xl bg-black/40 px-4 py-3 text-sm"/><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full text-sm text-slate-400"/><button className="rounded-xl bg-white px-5 py-3 font-semibold text-black">Publish resource</button></form>:<div className="mt-6 rounded-2xl border border-white/10 p-6 text-slate-500">Go to Academic, select Area → Program → Level → Subject, then return here.</div>}<div className="mt-8 grid gap-3">{resources.slice(0,20).map(r=><div key={r.id} className="rounded-xl border border-white/10 p-4"><b>{r.title}</b><span className="ml-2 text-xs text-indigo-300">{r.resource_type}</span></div>)}</div></section>}
  {tab==='showcases'&&<section><h1 className="text-3xl font-bold">Community Showcases</h1><div className="mt-6 space-y-3">{showcases.length===0&&<p className="text-slate-500">No submissions yet.</p>}{showcases.map(x=><div key={x.id} className="rounded-2xl border border-white/10 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{x.title}</h2><p className="mt-1 text-sm text-slate-400">{x.description}</p><p className="mt-2 text-xs text-slate-600">Status: {x.status}</p></div>{x.status==='pending'&&<div className="flex gap-2"><button onClick={()=>showcase(x.id,'approved')} className="rounded-lg bg-white px-3 py-2 text-sm text-black">Approve</button><button onClick={()=>showcase(x.id,'rejected')} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Reject</button></div>}</div></div>)}</div></section>}</main></div>;
}
